### ISSUE TITLE
How to upload this project to Render or any other deployment service

### ISSUE THREAD

**Issue by Terieyenike** [Terieyenike/linktree#1]

**Comment by oxone-999** [comment]
Hi, I can help you with this, please assign to me

**Comment by Terieyenike** [comment]
Thanks @oxone-999 for taking up this challenge.

**Comment by oxone-999** [comment]
For uploading this project to render i would be needing the environment variables also, can you provide that.
Or should I upload this project from your account, and in this case you don't have to share your .env file

**Comment by Terieyenike** [comment]
Can you create documentation for the process in the README? For environment variables, I haven't done anything to the project apart from viewing in localhost on port 8000.

Also, I know Render offers 90 days validity for hosting a project, and after the duration, it is deleted.

**Comment by oxone-999** [comment]
Okay sure, i will create

**Comment by oxone-999** [comment]
Please ,check, i have updated the read me file as you said

**Comment by Terieyenike** [comment]
Can you record your screen on deploying the project from start to finish?

@oxone-999

**Comment by Terieyenike** [comment]
Thanks for your help
