### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by Terieyenike** [Terieyenike/linktree#3]

**Comment by KaneshiroKeola** [comment]
Can i be assigned this task?

**Comment by Terieyenike** [comment]
Please go for it.

@KaneshiroKeola

**Comment by adiati98** [comment]
Hey @Terieyenike ,
Just a two cents here. It would be great if you could give some description on how you want to improve the documentation. That way, you can communicate your needs to contributors. 

If it's a large task, you can break it into smaller issues 🙂

**Comment by Terieyenike** [comment]
To be honest, I think the documentation is explanatory but would love further suggestions if any.

What do you think?

@adiati98

**Comment by Terieyenike** [comment]
> Hey @Terieyenike ,
> Just a two cents here. It would be great if you could give some description on how you want to improve the documentation. That way, you can communicate your needs to contributors. 
> 
> If it's a large task, you can break it into smaller issues 🙂

I may close the issue.

**Comment by adiati98** [comment]
@Terieyenike 

I'm not familiar with Django and PostgresQL, so I can't say much about the technical-wise docs.

But looking at the docs and `CONTRIBUTING.md` file, here are some of my thoughts:

- Is there any specific Django version to run this project? Then maybe you want to mention which version folks need to install before they can run this project locally and give the link to it.

- Is there any other frameworks that folks need to install besides Django?

- How to install and run this project locally after folks clone the repo?

- In the contributing guide, it's stated:

  > The [documentation] is open-source and built with Nuxt. You are very welcome to propose changes to it ...

  The documentation links to the `README.md` file. So it's not built with Nuxt? Which docs then can folks improve and what to improve?

- Still in the same section as above:

> ... and contribute to the Blog for Programming Nomads

  Is this project part of the Blog for Programming Nomads? A link to the blog would be handy.

- Is there any reason folks need to upload this project to render.com? 

And there are more things that I think folks need more clarification in the docs.

**Comment by adiati98** [comment]
> @Terieyenike 
> 
> I'm not familiar with Django and PostgresQL, so I can't say much about the technical-wise docs.
> 
> But looking at the docs and `CONTRIBUTING.md` file, here are some of my thoughts:
> 
> - Is there any specific Django version to run this project? Then maybe you want to mention which version folks need to install before they can run this project locally and give the link to it.
> 
> - Is there any other frameworks that folks need to install besides Django?
> 
> - How to install and run this project locally after folks clone the repo?
> 
> - In the contributing guide, it's stated:
> 
>   > The [documentation] is open-source and built with Nuxt. You are very welcome to propose changes to it ...
> 
>   The documentation links to the `README.md` file. So it's not built with Nuxt? Which docs then can folks improve and what to improve?
> 
> - Still in the same section as above:
> 
> > ... and contribute to the Blog for Programming Nomads
> 
>   Is this project part of the Blog for Programming Nomads? A link to the blog would be handy.
> 
> - Is there any reason folks need to upload this project to render.com? 
> 
> And there are more things that I think folks need more clarification in the docs.

My impression from the docs is that this project is a finished project, ready to use, and doesn't need contributions. But I could be wrong :)

**Comment by Terieyenike** [comment]
To be honest, I think the documentation is explanatory but would love further suggestions if any.

What do you think?

@adiati98 thanks for highlighting these points. I didn't check the mistakes you pointed and would make adjustments accordingly. 

The app is complete but want to add some features like the original Linktree app which I'd need some help with. 

Thanks for the second eye on my work.

**Comment by adiati98** [comment]
I'm happy to help, @Terieyenike! 😊

Also, if you want to add features, you can always create an issue for features you want to have. 

As long as the docs are clear, I believe this project is quite attractive for contributors who want to deep dive into Django 🙂

**Comment by Terieyenike** [comment]
Thanks for all your contributions.
